Controllers/CategoryController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using EmployeeClient.Models.Domain;
using EmployeeClient.Services.Interface;
using Microsoft.AspNetCore.Mvc;

namespace EmployeeClient.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryService categoryService;
        private readonly INotyfService notyfService;
        public CategoryController(ICategoryService categoryService, INotyfService notyfService)
        {
            this.categoryService = categoryService;
            this.notyfService = notyfService;
        }
        public IActionResult Index()
        {
            var currency = categoryService.GetAllCategories();
            return View(currency);
        }
        [HttpGet]
        public IActionResult Detail(int id)
        {
            var result = categoryService.GetCategoryById(id);
            return View(result);
        }
        [HttpGet]
        public IActionResult Create()
        {
            Category category = new Category();
            category.Status = "In-Active";
            return View(category);
        }
        [HttpPost]
        public IActionResult Create(Category category)
        {
            if (ModelState.IsValid)
            {
                var result = categoryService.CreateCategory(category);
                if (result != null)
                {
                    notyfService.Success("Category Created Successfully.");
                    return RedirectToAction("Index");
                }
                else
                {
                    notyfService.Error("Failed to Create Category!!");
                    return View(result);
                }
            }
            else
            {
                notyfService.Warning("Error at the Model EndPoint!!");
                return View(category);
            }
        }
        [HttpGet]
        public IActionResult Update(int id)
        {
            var category = categoryService.GetCategoryById(id);
            return View(category);
        }
        [HttpPost]
        public IActionResult Update(Category category)
        {
            if (ModelState.IsValid)
            {
                var result = categoryService.UpdateCategory(category);
                if (result != null)
                {
                    notyfService.Success("Category Updated Successfully.");
                    return RedirectToAction("Index");
                }
                else
                {
                    notyfService.Error("Failed to Update Category!!");
                    return View(result);
                }
            }
            else
            {
                notyfService.Warning("Error at the Model EndPoint!!");
                return View(category);
            }
        }
        public IActionResult Delete(int id)
        {
            categoryService.DeleteCategory(id);
            notyfService.Success("Category Deleted Successfully");
            return RedirectToAction("Index");
        }
    }
}

Controllers/InvoiceController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using EmployeeClient.Models.Domain;
using EmployeeClient.Services.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace EmployeeClient.Controllers
{
    public class InvoiceController : Controller
    {
        private readonly IInvoiceService invoiceService;
        private readonly IProductService productService;
        private readonly ICustomerService customerService;
        private readonly INotyfService notyfService;
        private readonly IDiscountService discountService;
        public InvoiceController(IInvoiceService invoiceService, IProductService productService, ICustomerService customerService, INotyfService notyfService, IDiscountService discountService)
        {
            this.invoiceService = invoiceService;
            this.productService = productService;
            this.customerService = customerService;
            this.notyfService = notyfService;
            this.discountService = discountService;
        }
        public IActionResult Index()
        {
            var result = invoiceService.GetAllInvoices();
            return View(result);
        }
        [HttpGet]
        public IActionResult Create()
        {
            Invoice invoice = new Invoice();
            ViewBag.Customer = customerService.GetAllCustomer().Select(x => new SelectListItem { Value = x.CustomerId.ToString(), Text = x.FirstName + " " + x.LastName }).ToList();
            ViewBag.Product = productService.GetAllProducts().Select(x => new SelectListItem { Value = x.ProductId.ToString(), Text = x.ProductName }).ToList();
            var getDiscount = discountService.GetAllDiscountList();
            var expiredDiscount = getDiscount.Where(x => x.ExpireDate == null || x.ExpireDate >= DateTime.Today);
            ViewBag.Discount = discountService.GetAllDiscountList().Where(x => x.ExpireDate == null || x.ExpireDate >= DateTime.Today).Select(x => new SelectListItem { Text = x.DiscountName + "-" + x.DiscountValue + "%", Value = x.DiscountId.ToString() }).ToList();
            ViewBag.DiscountValue = discountService.GetAllDiscountList().Select(x => new SelectListItem { Value = x.DiscountId.ToString(), Text = x.DiscountValue.ToString() }).ToList();
            ViewBag.GetBuyingPrice = productService.GetAllProducts().Select(x => new SelectListItem { Text = x.ProductBuyingPrice.ToString(), Value = x.ProductId.ToString() }).ToList();
            ViewBag.getVat = productService.GetAllProducts().Select(x => new SelectListItem { Text = x.ProductVat.ToString(), Value = x.ProductId.ToString() }).ToList();
            invoice.InvoiceDetails.Add(new InvoiceDetail() { InvoiceDetailId = 1 });
            invoice.InvoiceCode = invoiceService.InvoiceCodes();
            return View(invoice);
        }
        [HttpPost]
        public IActionResult Create(Invoice invoice)
        {
            ViewBag.Customer = customerService.GetAllCustomer().Select(x => new SelectListItem { Value = x.CustomerId.ToString(), Text = x.FirstName + " " + x.LastName, Selected = x.CustomerId == invoice.CustomerId }).ToList();
            ViewBag.Product = productService.GetAllProducts().Select(x => new SelectListItem { Value = x.ProductId.ToString(), Text = x.ProductName }).ToList();
            ViewBag.Discount = discountService.GetAllDiscountList().Where(x => x.ExpireDate == null || x.ExpireDate >= DateTime.Today).Select(x => new SelectListItem { Text = x.DiscountName + "-" + x.DiscountValue + "%", Value = x.DiscountId.ToString() }).ToList();
            ViewBag.DiscountValue = discountService.GetAllDiscountList().Select(x => new SelectListItem { Value = x.DiscountId.ToString(), Text = x.DiscountValue.ToString() }).ToList();
            ViewBag.GetBuyingPrice = productService.GetAllProducts().Select(x => new SelectListItem { Text = x.ProductSellingPrice.ToString(), Value = x.ProductId.ToString() }).ToList();
            ViewBag.getVat = productService.GetAllProducts().Select(x => new SelectListItem { Text = x.ProductVat.ToString(), Value = x.ProductId.ToString() }).ToList();
            if (ModelState.IsValid)
            {
                var result = invoiceService.CreateInvoice(invoice);
                if (result != null)
                {
                    notyfService.Success("Sales Invoice Created Successfully.");
                    return RedirectToAction("Index");
                }
                else
                {
                    notyfService.Error("Failed to Create Sales Invoice!!");
                    return View(result);
                }
            }
            else
            {
                notyfService.Warning("Model Error!!");
                return View(invoice);
            }
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var invoice = invoiceService.GetInvoiceById(id);
            ViewBag.Customer = customerService.GetAllCustomer().Select(x => new SelectListItem { Value = x.CustomerId.ToString(), Text = x.FirstName + " " + x.LastName, Selected = x.CustomerId == invoice.CustomerId }).ToList();
            ViewBag.Product = productService.GetAllProducts().Select(x => new SelectListItem { Value = x.ProductId.ToString(), Text = x.ProductName }).ToList();
            ViewBag.Discount = discountService.GetAllDiscountList().Where(x => x.ExpireDate == null || x.ExpireDate >= DateTime.Today).Select(x => new SelectListItem { Text = x.DiscountName + "-" + x.DiscountValue + "%", Value = x.DiscountId.ToString() }).ToList();
            ViewBag.DiscountValue = discountService.GetAllDiscountList().Select(x => new SelectListItem { Value = x.DiscountId.ToString(), Text = x.DiscountValue.ToString() }).ToList();
            ViewBag.GetBuyingPrice = productService.GetAllProducts().Select(x => new SelectListItem { Text = x.ProductBuyingPrice.ToString(), Value = x.ProductId.ToString() }).ToList();
            ViewBag.getVat = productService.GetAllProducts().Select(x => new SelectListItem { Text = x.ProductVat.ToString(), Value = x.ProductId.ToString() }).ToList();
            return View(invoice);
        }
        [HttpPost]
        public IActionResult Edit(Invoice invoice)
        {
            ViewBag.Customer = customerService.GetAllCustomer().Select(x => new SelectListItem { Value = x.CustomerId.ToString(), Text = x.FirstName + " " + x.LastName, Selected = x.CustomerId == invoice.CustomerId }).ToList();
            ViewBag.Product = productService.GetAllProducts().Select(x => new SelectListItem { Value = x.ProductId.ToString(), Text = x.ProductName }).ToList();
            ViewBag.Discount = discountService.GetAllDiscountList().Where(x => x.ExpireDate == null || x.ExpireDate >= DateTime.Today).Select(x => new SelectListItem { Text = x.DiscountName + "-" + x.DiscountValue + "%", Value = x.DiscountId.ToString() }).ToList();
            ViewBag.DiscountValue = discountService.GetAllDiscountList().Select(x => new SelectListItem { Value = x.DiscountId.ToString(), Text = x.DiscountValue.ToString() }).ToList();
            ViewBag.GetBuyingPrice = productService.GetAllProducts().Select(x => new SelectListItem { Text = x.ProductBuyingPrice.ToString(), Value = x.ProductId.ToString() }).ToList();
            ViewBag.getVat = productService.GetAllProducts().Select(x => new SelectListItem { Text = x.ProductVat.ToString(), Value = x.ProductId.ToString() }).ToList();
            if (ModelState.IsValid)
            {
                var result = invoiceService.UpdateInvoice(invoice);
                if (result != null)
                {
                    notyfService.Success("Sales Invoice Updated Successfully.");
                    return RedirectToAction("Index");
                }
                else
                {
                    notyfService.Error("Failed to Update Sales Invoices!!");
                    return View(result);
                }
            }
            else
            {
                notyfService.Warning("Model is Having Errors!!");
                return View(invoice);
            }
        }
        [HttpGet]
        public IActionResult Detail(int id)
        {
            var invoice = invoiceService.GetInvoiceById(id);
            ViewBag.Customer = customerService.GetAllCustomer().Select(x => new SelectListItem { Value = x.CustomerId.ToString(), Text = x.FirstName + " " + x.LastName, Selected = x.CustomerId == invoice.CustomerId }).ToList();
            ViewBag.Product = productService.GetAllProducts().Select(x => new SelectListItem { Value = x.ProductId.ToString(), Text = x.ProductName }).ToList();
            ViewBag.Discount = discountService.GetAllDiscountList().Select(x => new SelectListItem { Text = x.DiscountName + "-" + x.DiscountValue + "%", Value = x.DiscountId.ToString() }).ToList();
            ViewBag.DiscountValue = discountService.GetAllDiscountList().Select(x => new SelectListItem { Value = x.DiscountId.ToString(), Text = x.DiscountValue.ToString() }).ToList();
            ViewBag.GetBuyingPrice = productService.GetAllProducts().Select(x => new SelectListItem { Text = x.ProductBuyingPrice.ToString(), Value = x.ProductId.ToString() }).ToList();
            ViewBag.getVat = productService.GetAllProducts().Select(x => new SelectListItem { Text = x.ProductVat.ToString(), Value = x.ProductId.ToString() }).ToList();
            return View(invoice);
        }
        public IActionResult Delete(int id)
        {
            var result = invoiceService.DeleteInvoice(id);
            if (result)
            {
                notyfService.Success("Sales Invoices Deleted Successfully.");
                return RedirectToAction("Index");
            }
            else
            {
                notyfService.Error("Error Occurred While Deleting Sales Invoices!!");
                return View(result);
            }
        }
    }
}

Controllers/MeasureController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using EmployeeClient.Models.Domain;
using EmployeeClient.Services.Interface;
using Microsoft.AspNetCore.Mvc;

namespace EmployeeClient.Controllers
{
    public class MeasureController : Controller
    {
        private readonly IMeasureService measureService;
        private readonly INotyfService notyfService;
        public MeasureController(IMeasureService measureService, INotyfService notyfService)
        {
            this.measureService = measureService;
            this.notyfService = notyfService;
        }
        public IActionResult Index()
        {
            var measure = measureService.GetAllMeasure();
            return View(measure);
        }
        [HttpGet]
        public IActionResult Create()
        {
            MeasureUnit measure = new MeasureUnit();
            measure.Status = "In-Active";
            return View(measure);
        }
        [HttpPost]
        public IActionResult Create(MeasureUnit measure)
        {
            if (ModelState.IsValid)
            {
                var result = measureService.CreateMeasure(measure);
                if (result != null)
                {
                    notyfService.Success("Measure Unit Created Successfully.");
                    return RedirectToAction("Index");
                }
                else
                {
                    notyfService.Error("Failed to Create Measure Unit!!");
                    return View(result);
                }
            }
            else
            {
                notyfService.Warning("Error at the Model End!!");
                return View(measure);
            }
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var measure = measureService.GetMeasureById(id);
            return View(measure);
        }
        [HttpPost]
        public IActionResult Edit(MeasureUnit measure)
        {
            if (ModelState.IsValid)
            {
                var result = measureService.UpdateMeasure(measure);
                if (result != null)
                {
                    notyfService.Success("Measure Unit Updated Successfully.");
                    return RedirectToAction("Index");
                }
                else
                {
                    notyfService.Error("Failed to Update Measure Unit!!");
                    return View(result);
                }
            }
            else
            {
                notyfService.Warning("Error at the Model End!!");
                return View(measure);
            }
        }
        public IActionResult Delete(int id)
        {
            var result = measureService.DeleteMeasure(id);
            if (result)
            {
                notyfService.Success("Measure Unit Deleted Successfully.");
                return RedirectToAction("Index");
            }
            else
            {
                notyfService.Error("Error Occurred while Deleting Measure Unit!!!");
                return RedirectToAction("Index");
            }
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>PYMORE - @ViewData["Title"]</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    @*<link href="~/assets/img/favicon.png" rel="icon">*@
    <link href="~/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true">
    <link rel="stylesheet" href="~/css/select2.min.css" asp-append-version="true" />
    <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet" asp-append-version="true">
    <link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet" asp-append-version="true">
    <link href="~/assets/vendor/quill/quill.snow.css" rel="stylesheet" asp-append-version="true">
    <link href="~/assets/vendor/quill/quill.bubble.css" rel="stylesheet" asp-append-version="true">
    <link href="~/assets/vendor/remixicon/remixicon.css" rel="stylesheet" asp-append-version="true">
    <link href="~/assets/vendor/simple-datatables/style.css" rel="stylesheet" asp-append-version="true">

    <!-- Template Main CSS File -->
    <link href="~/assets/css/style.css" rel="stylesheet" asp-append-version="true">
</head>

<body>

    <!-- ======= Header ======= -->
    <header id="header" class="header fixed-top d-flex align-items-center">

        <div class="d-flex align-items-center justify-content-between">
            <a href="#" class="logo d-flex align-items-center"><img src="~/assets/img/logo.png" alt=""><span class="d-none d-lg-block">PYMORE</span></a>
            <i class="bi bi-list toggle-sidebar-btn"></i>
        </div><!-- End Logo -->

        <div class="search-bar">
            <form class="search-form d-flex align-items-center" method="POST" action="#">
                <input type="text" name="query" placeholder="Search" title="Enter search keyword">
                <button type="submit" title="Search"><i class="bi bi-search"></i></button>
            </form>
        </div><!-- End Search Bar -->

        <nav class="header-nav ms-auto">
            <ul class="d-flex align-items-center">

                <li class="nav-item d-block d-lg-none">
                    <a class="nav-link nav-icon search-bar-toggle " href="#">
                        <i class="bi bi-search"></i>
                    </a>
                </li><!-- End Search Icon-->

                <li class="nav-item dropdown pe-3">

                    <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
                        <img src="~/assets/img/face15.jpg" alt="Profile" class="rounded-circle">
                        <span class="d-none d-md-block dropdown-toggle ps-2">M. Gathoni</span>
                    </a><!-- End Profile Iamge Icon -->

                    <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
                        <li class="dropdown-header">
                            <h6>Mburu Gathoni</h6>
                            <span>Web Designer</span>
                        </li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item d-flex align-items-center" href="#"><i class="bi bi-person"></i><span>My Profile</span></a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item d-flex align-items-center" href="#"><i class="bi bi-gear"></i><span>Account Settings</span></a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item d-flex align-items-center" href="#"><i class="bi bi-question-circle"></i><span>Need Help?</span></a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item d-flex align-items-center" href="#"><i class="bi bi-box-arrow-right"></i><span>Sign Out</span></a></li>

                    </ul><!-- End Profile Dropdown Items -->
                </li><!-- End Profile Nav -->

            </ul>
        </nav><!-- End Icons Navigation -->

    </header><!-- End Header -->
    <!-- ======= Sidebar ======= -->
    <aside id="sidebar" class="sidebar">

        <ul class="sidebar-nav" id="sidebar-nav">

            <li class="nav-item"><a class="nav-link collapsed" href="#"><i class="bi bi-grid"></i><span>Dashboard</span></a></li><!-- End Dashboard Nav -->

            <li class="nav-item">
                <a class="nav-link collapsed" data-bs-target="#tables-nav" data-bs-toggle="collapse" href="#">
                    <i class="bi bi-layout-text-window-reverse"></i><span>Inventory</span><i class="bi bi-chevron-down ms-auto"></i>
                </a>
                <ul id="tables-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                    <li><a asp-area="" asp-controller="Product" asp-action="Index"><i class="bi bi-circle"></i><span>Product</span></a></li>
                    <li><a asp-area="" asp-controller="Category" asp-action="Index"><i class="bi bi-circle"></i><span>Category</span></a></li>
                    <li><a asp-area="" asp-controller="Currency" asp-action="Index"><i class="bi bi-circle"></i><span>Currency</span></a></li>
                    <li><a asp-area="" asp-controller="Measure" asp-action="Index"><i class="bi bi-circle"></i><span>Measure Unit</span></a></li>
                    <li><a asp-area="" asp-controller="Discount" asp-action="Index"><i class="bi bi-circle"></i><span>Discount</span></a></li>
                </ul>
            </li><!-- End Tables Nav -->

            <li class="nav-item">
                <a class="nav-link collapsed" data-bs-target="#charts-nav" data-bs-toggle="collapse" href="#">
                    <i class="bi bi-bar-chart"></i><span>Sales</span><i class="bi bi-chevron-down ms-auto"></i>
                </a>
                <ul id="charts-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                    <li><a asp-area="" asp-controller="Customer" asp-action="Index"><i class="bi bi-circle"></i><span>Customers</span></a></li>
                    <li><a asp-area="" asp-controller="Invoice" asp-action="Index"><i class="bi bi-circle"></i><span>Sales Invoices</span></a></li>
                </ul>
            </li><!-- End Charts Nav -->

            <li class="nav-item">
                <a class="nav-link collapsed" data-bs-target="#icons-nav" data-bs-toggle="collapse" href="#">
                    <i class="bi bi-bar-chart"></i><span>Purchases</span><i class="bi bi-chevron-down ms-auto"></i>
                </a>
                <ul id="icons-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                    <li><a asp-area="" asp-controller="Supplier" asp-action="Index"><i class="bi bi-circle"></i><span>Suppliers</span></a></li>
                    <li><a asp-area="" asp-controller="HeaderInvoice" asp-action="Index"><i class="bi bi-circle"></i><span>Purchase Invoice</span></a></li>
                    <li><a asp-area="" asp-controller="GoodReceived" asp-action="Index"><i class="bi bi-circle"></i><span>Goods Received</span></a></li>
                </ul>
            </li><!-- End Icons Nav -->



        </ul>

    </aside><!-- End Sidebar-->

    <main id="main" class="main">

        <div class="pagetitle">
            <h1>Blank Page</h1>
            <nav>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                    <li class="breadcrumb-item">Pages</li>
                    <li class="breadcrumb-item active">Blank</li>
                </ol>
            </nav>
        </div><!-- End Page Title -->

        <section class="section">
            <div class="row">
                <div class="col-lg-12">

                    <div class="card">
                        @RenderBody()
                    </div>

                </div>
            </div>
        </section>

    </main><!-- End #main -->
    <!-- ======= Footer ======= -->
    <footer id="footer" class="footer">
        <div class="copyright">
            &copy; Copyright <strong><span>NgenX</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
            Designed by <a href="#">Mburu G.</a>
        </div>
    </footer><!-- End Footer -->

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <!-- Vendor JS Files -->
    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/assets/vendor/apexcharts/apexcharts.min.js" asp-append-version="true"></script>
    <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js" asp-append-version="true"></script>
    <script src="~/js/select2.min.js" asp-append-version="true"></script>
    <script src="~/assets/vendor/chart.js/chart.umd.js" asp-append-version="true"></script>
    <script src="~/assets/vendor/echarts/echarts.min.js" asp-append-version="true"></script>
    <script src="~/assets/vendor/quill/quill.min.js" asp-append-version="true"></script>
    <script src="~/assets/vendor/simple-datatables/simple-datatables.js" asp-append-version="true"></script>
    <script src="~/assets/vendor/tinymce/tinymce.min.js" asp-append-version="true"></script>
    <script src="~/assets/vendor/php-email-form/validate.js" asp-append-version="true"></script>

    <!-- Template Main JS File -->
    <script src="~/assets/js/main.js" asp-append-version="true"></script>
    @await Component.InvokeAsync("Notyf");
    @await RenderSectionAsync("Scripts", required: false);
</body>

</html>