Models/Domain/Currency.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EmployeeClient.Models.Domain
{
    public class Currency
    {
        public int CurrencyId { get; set; }
        [Display(Name = "Currency Name")]
        public string CurrencyName { get; set; } = string.Empty;
        public string Abbreviation { get; set; } = string.Empty;
        [Column(TypeName = "decimal(18, 3)")]
        [Display(Name = "Exchange Rate")]
        public decimal ExchangeRate { get; set; }
        [Display(Name = "Country Name")]
        public string CountryName { get; set; } = string.Empty;
        public string Status { get; set; } = string.Empty;
    }
}

Controllers/CurrencyController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using EmployeeClient.Models.Domain;
using EmployeeClient.Services.Interface;
using Microsoft.AspNetCore.Mvc;

namespace EmployeeClient.Controllers
{
    public class CurrencyController : Controller
    {
        private readonly ICurrencyService currencyService;
        private readonly INotyfService notyfService;
        public CurrencyController(ICurrencyService currencyService, INotyfService notyfService)
        {
            this.currencyService = currencyService;
            this.notyfService = notyfService;
        }
        public IActionResult Index()
        {
            var currency = currencyService.GetAllCurrency();
            return View(currency);
        }
        [HttpGet]
        public IActionResult Create()
        {
            Currency currency = new Currency();
            currency.Status = "In-Active";
            return View(currency);
        }
        [HttpPost]
        public IActionResult Create(Currency currency)
        {
            if (ModelState.IsValid)
            {
                var result = currencyService.CreateCurrency(currency);
                if (result != null)
                {
                    notyfService.Success("Currency Created Successfully");
                    return RedirectToAction("Index");
                }
                else
                {
                    notyfService.Error("Failed to Create Currency!!");
                    return View(result);
                }
            }
            else
            {
                notyfService.Warning("Error at the Model End.");
                return View(currency);
            }
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var currency = currencyService.GetCurrencyById(id);
            return View(currency);
        }
        [HttpPost]
        public IActionResult Edit(Currency currency)
        {
            if (ModelState.IsValid)
            {
                var result = currencyService.UpdateCurrency(currency);
                if (result != null)
                {
                    notyfService.Success("Currency Updated Successfully");
                    return RedirectToAction("Index");
                }
                else
                {
                    notyfService.Error("Failed to Update Currency!!");
                    return View(result);
                }
            }
            else
            {
                notyfService.Warning("Error at the Model End.");
                return View(currency);
            }
        }
        public IActionResult Delete(int id)
        {
            currencyService.DeleteCurrency(id);
            notyfService.Success("Currency Deleted Successful");
            return RedirectToAction("Index");
        }
    }
}

Views/Currency/Create.cshtml
@model EmployeeClient.Models.Domain.Currency
@{
    ViewData["Title"] = "Create Currency";
}
<div class="card-header">
    <h4 style="font-family: monospace; font-weight: bold;">Creating New Currency</h4>
</div>
<div class="card-body">
    <form asp-controller="Currency" asp-action="Create">
        <div class="text-danger" asp-validation-summary="ModelOnly"></div>
        <div class="col-md-8">
            <div class="form-group">
                <label style="font-family: monospace; font-weight: bold;" class="form-label" asp-for="CurrencyName"></label>
                <input class="form-control" asp-for="CurrencyName" oninput="this.value = this.value.toUpperCase()" />
                <span class="text-danger" asp-validation-for="CurrencyName"></span>
            </div>
            <div class="form-group">
                <label style="font-family: monospace; font-weight: bold;" class="form-label" asp-for="Abbreviation"></label>
                <input class="form-control" asp-for="Abbreviation" oninput="this.value = this.value.toUpperCase()" />
                <span class="text-danger" asp-validation-for="Abbreviation"></span>
            </div>
            <div class="form-group">
                <label style="font-family: monospace; font-weight: bold;" class="form-label" asp-for="ExchangeRate"></label>
                <input class="form-control" asp-for="ExchangeRate" />
                <span class="text-danger" asp-validation-for="ExchangeRate"></span>
            </div>
            <div class="form-group">
                <label style="font-family: monospace; font-weight: bold;" class="form-label" asp-for="CountryName"></label>
                <input class="form-control" asp-for="CountryName" oninput="this.value = this.value.toUpperCase()" />
                <span class="text-danger" asp-validation-for="CountryName"></span>
            </div>
            <input type="hidden" asp-for="Status" />
            <div class="form-group pull-right pt-3">
                <button class="btn btn-primary" type="submit"><i class="fa fa-plus-square-o"></i> Currency</button>
                <a class="btn btn-danger" asp-controller="Currency" asp-action="Index"><i class="fa fa-close"></i></a>
            </div>
        </div>
    </form>
</div>

Views/Currency/Edit.cshtml
@model EmployeeClient.Models.Domain.Currency
@{
    ViewData["Title"] = "Edit Currency";
}
<div class="card-header">
    <h4 style="font-family: monospace; font-weight: bold;">Updating Currency</h4>
</div>
<div class="card-body">
    <form asp-controller="Currency" asp-action="Edit">
        <div class="text-danger" asp-validation-summary="ModelOnly"></div>
        <div class="col-md-8">
            <input type="hidden" asp-for="CurrencyId" />
            <div class="form-group">
                <label style="font-family: monospace; font-weight: bold;" class="form-label" asp-for="CurrencyName"></label>
                <input class="form-control" asp-for="CurrencyName" oninput="this.value = this.value.toUpperCase()" />
                <span class="text-danger" asp-validation-for="CurrencyName"></span>
            </div>
            <div class="form-group">
                <label style="font-family: monospace; font-weight: bold;" class="form-label" asp-for="Abbreviation"></label>
                <input class="form-control" asp-for="Abbreviation" oninput="this.value = this.value.toUpperCase()" />
                <span class="text-danger" asp-validation-for="Abbreviation"></span>
            </div>
            <div class="form-group">
                <label style="font-family: monospace; font-weight: bold;" class="form-label" asp-for="ExchangeRate"></label>
                <input class="form-control" asp-for="ExchangeRate" />
                <span class="text-danger" asp-validation-for="ExchangeRate"></span>
            </div>
            <div class="form-group">
                <label style="font-family: monospace; font-weight: bold;" class="form-label" asp-for="CountryName"></label>
                <input class="form-control" asp-for="CountryName" oninput="this.value = this.value.toUpperCase()" />
                <span class="text-danger" asp-validation-for="CountryName"></span>
            </div>
            <div class="form-group">
                <label style="font-family: monospace; font-weight: bold;" class="form-label" asp-for="Status"></label>
                <select class="form-control form-control-sm form-select form-select-sm select2 statusSelect" asp-for="Status">
                    <option>Choose Status</option>
                    <option>Active</option>
                    <option>In-Active</option>
                </select>
                <span class="text-danger" asp-validation-for="Status"></span>
            </div>
            <div class="form-group pull-right pt-3">
                <button class="btn btn-success" type="submit"><i class="fa fa-edit"></i> Currency</button>
                <a class="btn btn-danger" asp-controller="Currency" asp-action="Index"><i class="fa fa-close"></i></a>
            </div>
        </div>
    </form>
</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script type="text/javascript">
        $(document).ready(function () {
            $('.statusSelect').select2();
        });
    </script>
}

Views/Currency/Index.cshtml
@using EmployeeClient.Models.Domain;
@model IEnumerable<Currency>
@{
    ViewData["Title"] = "Currency List";
}
<div class="card-header">
    <div class="row">
        <div class="col-md-2"><h4 style="font-family: monospace; font-weight: bold;">All Currency List</h4></div>
        <div class="col-md-8"></div>
        <div class="col-md-2">
            <div class="form-group pull-right"><a class="btn btn-primary btn-sm" style="font-family: monospace; font-weight: bold;" asp-controller="Currency" asp-action="Create"><i class="fa fa-plus-circle"></i> New Currency</a></div>
        </div>
    </div>
</div>
<div class="table-responsive">
    <table class="table dataTable">
        <thead>
            <tr>
                <th>REF</th>
                <th>Name</th>
                <th>ABREV</th>
                <th>Rate</th>
                <th>Country</th>
                <th>Status</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var currency in Model)
            {
                <tr>
                    <td>@currency.CurrencyId</td>
                    <td>@currency.CurrencyName</td>
                    <td>@currency.Abbreviation</td>
                    <td>@currency.ExchangeRate</td>
                    <td>@currency.CountryName</td>
                    @if (currency.Status == "Active")
                    {
                        <td><span class="text-success"><i class="fa fa-check-circle-o" aria-hidden="true"> @currency.Status</i></span></td>
                    }
                    else
                    {
                        <td><span class="text-danger"><i class="fa fa-check-circle-o" aria-hidden="true"> @currency.Status</i></span></td>
                    }
                    <td>
                        <select class="form-select form-select-sm form-control" style="font-size: 12px; font-family: monospace; font-weight: bold; height: 30px;" onchange="ActionChange(event)">
                            <option value="">Choose Action</option>
                            <option value="@Url.Action("Edit","Currency", new { id = currency.CurrencyId })">Edit Currency</option>
                        </select>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
@await Html.PartialAsync("_CreateCurrency", new Currency())
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script type="text/javascript">
        function ActionChange(event) {
            var selectEvent = event.target;
            var value = selectEvent.value;
            if (value.startsWith("/Currency/Edit/")) {
                window.location.href = value;
            }
        }
    </script>
}

Views/Currency/_CreateCurrency.cshtml
@model EmployeeClient.Models.Domain.Currency

<div class="modal fade" id="addCurrency" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Create Currency</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
                <form asp-action="Create" method="post">
                    <div class="text-danger" asp-validation-summary="ModelOnly"></div>
                    <div class="form-group">
                        <label class="form-label" asp-for="CurrencyName"></label>
                        <input class="form-control" asp-for="CurrencyName" oninput="this.value = this.value.toUpperCase()" />
                        <span class="text-danger" asp-validation-for="CurrencyName"></span>
                    </div>
                    <div class="form-group">
                        <label class="form-label" asp-for="Abbreviation"></label>
                        <input class="form-control" asp-for="Abbreviation" oninput="this.value = this.value.toUpperCase()" />
                        <span class="text-danger" asp-validation-for="Abbreviation"></span>
                    </div>
                    <div class="form-group">
                        <label class="form-label" asp-for="ExchangeRate"></label>
                        <input class="form-control" asp-for="ExchangeRate" />
                        <span class="text-danger" asp-validation-for="ExchangeRate"></span>
                    </div>
                    <div class="form-group">
                        <label class="form-label" asp-for="CountryName"></label>
                        <input class="form-control" asp-for="CountryName" oninput="this.value = this.value.toUpperCase()" />
                        <span class="text-danger" asp-validation-for="CountryName"></span>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary"><i class="fa fa-plus-square-o"></i> Create</button>
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"><i class="fa fa-close"></i></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>